### PR TITLE
Fixes invalid dates being returned from holiday list

### PR DESCRIPTION
**Pull request by keithpops**
Adjusts date parsing for single digit months / days which resolves invalid dates being returned in the holiday list.

### CODE REVIEW

**Comment by mgwalker** [comment]
Hi @keithpops! Thanks for opening this PR! Can you tell me a little more about how to trigger the bug you're fixing? I want to make sure we add/update tests to catch it so we don't have a regression someday.

**Comment by keithpops** [comment]
Hi @mgwalker and thanks for reviewing. I am able to recreate the error when attempting to use the dayjs `customParseFormat` plugin outside of this package like so:

```
const customParseFormat = require('dayjs/plugin/customParseFormat')

dayjs.extend(customParseFormat)
```

Adding this line to the [index.js](https://github.com/18F/us-federal-holidays/blob/main/index.js) will cause the tests to fail.

**Comment by mgwalker** [comment]
Oooh, so it's a compatibility issue? Interesting! This is a great catch, thanks! We definitely don't want to create problems when used alongside other dayjs plugins. I'll get this merged and published in the next hour or two.

Would you mind if I add you to the list of contributors in the `package.json`?

**Comment by keithpops** [comment]
No problem, @mgwalker! The plugin introduces [strict date parsing](https://dayjs.gitee.io/docs/en/parse/string-format) by default so days or months with single digits likely need to be zero-padded with `YYYY-MM-DD` format. Adjusting the format should be enough to make it work.

Happy to be added as a contributor!

**Review by mgwalker — APPROVED** [review]

**Pull request merged**
