### PR TITLE
[WIP] Fix: May 31th is not recognised as a holiday in 2021

### LINKED ISSUE #28: Wrong Memorial Day for Year 2021
## What did I do
```js
const fedHolidays = require("@18f/us-federal-holidays");

const options = { shiftSaturdayHolidays: true, shiftSundayHolidays: true };
const holidays = fedHolidays.allForYear(2021, options);

console.log(holidays)
```

## What did I get
```json
[
  {
    "name": "New Year's Day",
    "date": "2021-01-01T00:00:00.000Z",
    "dateString": "2021-1-1"
  },
  {
    "name": "Birthday of Martin Luther King, Jr.",
    "date": "2021-01-18T00:00:00.000Z",
    "dateString": "2021-1-18"
  },
  {
    "name": "Washington's Birthday",
    "date": "2021-02-15T00:00:00.000Z",
    "dateString": "2021-2-15"
  },
  {
    "name": "Memorial Day", // Look at this
    "date": "2021-05-24T00:00:00.000Z",
    "dateString": "2021-5-24"
  },
  {
    "name": "Juneteenth National Independence Day",
    "date": "2021-06-18T00:00:00.000Z",
    "dateString": "2021-6-18"
  },
  {
    "name": "Independence Day",
    "date": "2021-07-05T00:00:00.000Z",
    "dateString": "2021-7-5"
  },
  {
    "name": "Labor Day",
    "date": "2021-09-06T00:00:00.000Z",
    "dateString": "2021-9-6"
  },
  {
    "name": "Columbus Day",
    "date": "2021-10-11T00:00:00.000Z",
    "dateString": "2021-10-11"
  },
  {
    "name": "Veterans Day",
    "date": "2021-11-11T00:00:00.000Z",
    "dateString": "2021-11-11"
  },
  {
    "name": "Thanksgiving Day",
    "date": "2021-11-25T00:00:00.000Z",
    "dateString": "2021-11-25"
  },
  {
    "name": "Christmas Day",
    "date": "2021-12-24T00:00:00.000Z",
    "dateString": "2021-12-24"
  }
]
```

Memorial Day is set at `2021-05-24`

## What do I expect
Memorial Day should be at [`2021-05-31`](https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/#url=2021)

### PR DESCRIPTION
**Pull request by tsekityam**
Fix #28

### CODE REVIEW

**Comment by tsekityam** [comment]
When I ran `npm test`, all the tests passed, no idea when it fails with CI.
<details>
  <summary>Click to expand terminal output</summary>
  
```sh
tsekityam@MacBook-Pro-Mike us-federal-holidays % npm test

> @18f/us-federal-holidays@2.0.0 test /Users/tsekityam/GitHub/us-federal-holidays
> tap --reporter=spec index.test.js


index.test.js
  handles standard federal holidays
    gets observed holidays, accounting for actual holidays on weekends
      ✓ 2010-12-31 is a holiday (observed)
      ✓ 2010-12-31 UTC is a holiday (observed)
      ✓ 2012-01-02 is a holiday (observed)
      ✓ 2012-01-02 UTC is a holiday (observed)
      ✓ 2014-01-01 is a holiday (observed)
      ✓ 2014-01-01 UTC is a holiday (observed)
      ✓ 2014-01-20 is a holiday (observed)
      ✓ 2014-01-20 UTC is a holiday (observed)
      ✓ 2014-02-17 is a holiday (observed)
      ✓ 2014-02-17 UTC is a holiday (observed)
      ✓ 2014-05-26 is a holiday (observed)
      ✓ 2014-05-26 UTC is a holiday (observed)
      ✓ 2014-07-04 is a holiday (observed)
      ✓ 2014-07-04 UTC is a holiday (observed)
      ✓ 2014-09-01 is a holiday (observed)
      ✓ 2014-09-01 UTC is a holiday (observed)
      ✓ 2014-10-13 is a holiday (observed)
      ✓ 2014-10-13 UTC is a holiday (observed)
      ✓ 2014-11-11 is a holiday (observed)
      ✓ 2014-11-11 UTC is a holiday (observed)
      ✓ 2014-11-27 is a holiday (observed)
      ✓ 2014-11-27 UTC is a holiday (observed)
      ✓ 2014-12-25 is a holiday (observed)
      ✓ 2014-12-25 UTC is a holiday (observed)
      ✓ 2015-07-03 is a holiday (observed)
      ✓ 2015-07-03 UTC is a holiday (observed)
      ✓ 2016-12-26 is a holiday (observed)
      ✓ 2016-12-26 UTC is a holiday (observed)
      ✓ 2017-12-25 is a holiday (observed)
      ✓ 2017-12-25 UTC is a holiday (observed)
      ✓ 2021-05-31 is a holiday (observed)
      ✓ 2021-05-31 UTC is a holiday (observed)
    actual holidays on weekends are not listed as observed holidays
      ✓ 2011-01-01 is not a holiday (observed)
      ✓ 2011-01-01 UTC is not a holiday (observed)
      ✓ 2012-01-01 is not a holiday (observed)
      ✓ 2012-01-01 UTC is not a holiday (observed)
      ✓ 2015-07-04 is not a holiday (observed)
      ✓ 2015-07-04 UTC is not a holiday (observed)
      ✓ 2016-12-25 is not a holiday (observed)
      ✓ 2016-12-25 UTC is not a holiday (observed)
      ✓ 2021-05-24 is not a holiday (observed)
      ✓ 2021-05-24 UTC is not a holiday (observed)
    Juneteenth is only included from 2021 onwards
      ✓ Juneteenth is not a holiday in 2020
      ✓ Juneteenth is a holiday in 2021
      ✓ Juneteenth is a holiday in 2023
      ✓ Juneteenth is not included in the list of holidays for 2020
      ✓ Juneteenth is included in the list of holidays for 2021
    honors requests not to shift holidays on weekends
      ✓ 2011-01-01 is a holiday if Sundays are not shifted
      ✓ 2012-01-01 is a holiday if Sundays are not shifted
      ✓ 2015-07-04 is a holiday if Saturdays are not shifted
      ✓ 2016-12-25 is a holiday if Saturdays are not shifted
    handles federal holidays within a range (Saturday and Sunday holidays shifted)
      ✓ 2015-7-3 is a holiday (observed)
      ✓ 2015-9-7 is a holiday (observed)
      ✓ 2015-10-12 is a holiday (observed)
      ✓ 2015-11-11 is a holiday (observed)
      ✓ 2015-11-26 is a holiday (observed)
      ✓ 2015-12-25 is a holiday (observed)
      ✓ 2016-1-1 is a holiday (observed)
      ✓ 2016-1-18 is a holiday (observed)
      ✓ 2016-2-15 is a holiday (observed)
      ✓ 2016-5-30 is a holiday (observed)
      ✓ 2016-7-4 is a holiday (observed)
      ✓ 2016-9-5 is a holiday (observed)
      ✓ 2016-10-10 is a holiday (observed)
      ✓ 2016-11-11 is a holiday (observed)
      ✓ 2016-11-24 is a holiday (observed)
      ✓ 2016-12-26 is a holiday (observed)
    handles federal holidays within a range (Saturday shifted only)
      ✓ 2015-7-3 is a holiday (observed)
      ✓ 2015-9-7 is a holiday (observed)
      ✓ 2015-10-12 is a holiday (observed)
      ✓ 2015-11-11 is a holiday (observed)
      ✓ 2015-11-26 is a holiday (observed)
      ✓ 2015-12-25 is a holiday (observed)
      ✓ 2016-1-1 is a holiday (observed)
      ✓ 2016-1-18 is a holiday (observed)
      ✓ 2016-2-15 is a holiday (observed)
      ✓ 2016-5-30 is a holiday (observed)
      ✓ 2016-7-4 is a holiday (observed)
      ✓ 2016-9-5 is a holiday (observed)
      ✓ 2016-10-10 is a holiday (observed)
      ✓ 2016-11-11 is a holiday (observed)
      ✓ 2016-11-24 is a holiday (observed)
      ✓ 2016-12-25 is a holiday (observed)
    handles federal holidays within a range (Sunday shifted only)
      ✓ 2015-7-4 is a holiday (observed)
      ✓ 2015-9-7 is a holiday (observed)
      ✓ 2015-10-12 is a holiday (observed)
      ✓ 2015-11-11 is a holiday (observed)
      ✓ 2015-11-26 is a holiday (observed)
      ✓ 2015-12-25 is a holiday (observed)
      ✓ 2016-1-1 is a holiday (observed)
      ✓ 2016-1-18 is a holiday (observed)
      ✓ 2016-2-15 is a holiday (observed)
      ✓ 2016-5-30 is a holiday (observed)
      ✓ 2016-7-4 is a holiday (observed)
      ✓ 2016-9-5 is a holiday (observed)
      ✓ 2016-10-10 is a holiday (observed)
      ✓ 2016-11-11 is a holiday (observed)
      ✓ 2016-11-24 is a holiday (observed)
      ✓ 2016-12-26 is a holiday (observed)
    handles federal holidays within a range (none shifted)
      ✓ 2015-7-4 is a holiday (observed)
      ✓ 2015-9-7 is a holiday (observed)
      ✓ 2015-10-12 is a holiday (observed)
      ✓ 2015-11-11 is a holiday (observed)
      ✓ 2015-11-26 is a holiday (observed)
      ✓ 2015-12-25 is a holiday (observed)
      ✓ 2016-1-1 is a holiday (observed)
      ✓ 2016-1-18 is a holiday (observed)
      ✓ 2016-2-15 is a holiday (observed)
      ✓ 2016-5-30 is a holiday (observed)
      ✓ 2016-7-4 is a holiday (observed)
      ✓ 2016-9-5 is a holiday (observed)
      ✓ 2016-10-10 is a holiday (observed)
      ✓ 2016-11-11 is a holiday (observed)
      ✓ 2016-11-24 is a holiday (observed)
      ✓ 2016-12-25 is a holiday (observed)
    handles default dates and ranges
      indicates whether today is a holiday
        ✓ is not a holiday
      fetches all holidays for the current year
        ✓ gets the expected holidays
        ✓ gets exactly the expected holidays
      defaults to a range from now to one year from now
        ✓ get the expected holidays
        ✓ gets exactly the expected holidays


  120 passing (420.484ms)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.js |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
```
</details>

I tried run with GitHub Actions, and it fails with both node 12, 14 and 16. 

When I printed `const daysInMonth = new Date(2021, 5).getUTCDate() - 7;`, it got `-6` in GitHub Action, but `31` in my MacBook. Seems that we failed to get the date.

I need some time to investigate the issue.

**Comment by mgwalker** [comment]
Well this is very interesting. Your new test to catch this situation is great, thank you! When I check out your code, the tests fail, but if I revert the change in `index.js` to be `Date(year, month, 0)` again, the tests pass, including the May 31, 2021 holiday.

Can you say more about the environment you're running in? I see in your profile that you are located in Hong Kong and I wonder if there is a timezone-related issue. When I originally created this library, I was lazy and only focused on making sure it would work in US timezones. Maybe it's time to reconsider making it fully UTC compatible. 😄

**Comment by tsekityam** [comment]
@mgwalker , yes, it is timezone related issue. see my comment on https://github.com/18F/us-federal-holidays/issues/28#issuecomment-890079851.

Do you mind adding 3rd party library, such as `dayjs`, `luxon` or `date-fns` as dependency? If so, I can help making the library works with non-US timezone.

**Comment by mgwalker** [comment]
One of the design goals was not to have any 3rd-party dependencies, but that was mostly because Moment.js was so large. Eventually, it would be nice to use the [Temporal API](https://github.com/tc39/proposal-temporal) once that's widely available, but until then...  dayjs looks quite small! If you're interested in giving a shot, I'm open to it! 😄

**Pull request closed without merging**
